<div style="background-color: #eeeeee;width:auto;margin:auto;text-align: center;">
    <div>
        <p style="font-weight: bolder;">Admin Authentication</p>
    </div>
         <?php
$form = $this->form;
$form->setAttribute('action', $this->url('Admin', array('action' => 'login')));
$form->prepare();

echo $this->form()->openTag($form); 
?>
        <table align="center">
            <tbody>
               
                <tr>
                    <td>Login : </td><td><?php echo $this->formRow($form->get('username')); ?></td>
                </tr>
                <tr>
                    <td>Password : </td><td><?php echo $this->formRow($form->get('password')); ?></td>
                </tr>
            </tbody>
        </table>
<?php 

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag(); 

?>
        
   
</div>